import { CreateLeadInput } from '@/lib/types/lead';
import { LeadStatus, AdSpendIntensity, RiskLevel } from '@/lib/models/Lead';

export const sampleLeads: CreateLeadInput[] = [
  {
    advertiser: "Watchastic Bangladesh",
    facebook_link: "https://www.facebook.com/asticBD/",
    website_link: "FB Only",
    contact: "",
    library_id: "2371749923242192",
    probability: 70,
    service: "E-commerce website development and maintenance",
    reasoning: "Watchastic Bangladesh is a local, active retailer with 13K followers a…",
    issues: "",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "Low (<30%)",
    status: LeadStatus.NEW,
    tags: ["retail"],
    pitch: "সালামু আলাইকুম, Watchastic Bangladesh! আপনি FB-এ বিক্রি করছেন — কিন্ত…",
    whatsapp_link: "",
    notes: [],
  },
  {
    advertiser: "Aarong",
    facebook_link: "https://www.facebook.com/BRAC.AARONG/",
    website_link: "FB Only",
    contact: "",
    library_id: "1157634265996949",
    probability: 12,
    service: "Security audits for websites and apps",
    reasoning: "Aarong is a massive, well‑established retailer with millions of follow…",
    issues: "FB-only store — perfect for AI Chatbot + Auto-Order System",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "Low (<30%)",
    status: LeadStatus.NEW,
    tags: ["retail"],
    pitch: "সালামু আলাইকুম, Aarong! আপনি FB-এ বিক্রি করছেন — কিন্তু অর্ডার ম্যানু…",
    whatsapp_link: "",
    notes: [],
  },
  {
    advertiser: "EYESPACE22.COM",
    facebook_link: "https://www.facebook.com/eyespace22/",
    website_link: "https://eyespace22.com",
    contact: "+880 1325-405369",
    library_id: "4032794660384557",
    probability: 65,
    service: "Securing and maintaining existing online stores",
    reasoning: "EyeSpace22 is an active local eyewear retailer with a 31K‑follower Fac…",
    issues: "Missing headers: Missing CSP",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "High (70%+)",
    status: LeadStatus.CONTACTED,
    tags: ["eyewear"],
    pitch: "সালামু আলাইকুম, EYESPACE22.COM! হ্যাকাররা আপনার সাইটে ঢুকতে পারে — সি…",
    whatsapp_link: "",
    notes: [],
  },
  {
    advertiser: "Fabrilife",
    facebook_link: "https://www.facebook.com/fabrilife/",
    website_link: "FB Only",
    contact: "+8809677666888",
    library_id: "2094084998026872",
    probability: 15,
    service: "Security audits for websites and apps",
    reasoning: "Fabrilife is a large, well‑established clothing brand with 850K follow…",
    issues: "FB-only store — perfect for AI Chatbot + Auto-Order System",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "Medium (50%)",
    status: LeadStatus.QUALIFIED,
    tags: ["clothing"],
    pitch: "সালামু আলাইকুম, Fabrilife! আপনি FB-এ বিক্রি করছেন — কিন্তু অর্ডার ম্য…",
    whatsapp_link: "",
    notes: [],
  },
  {
    advertiser: "Royal Malabar - Fashion Mall",
    facebook_link: "https://www.facebook.com/RoyalMalabarFashionMall/",
    website_link: "FB Only",
    contact: "01311-183899",
    library_id: "736090942840644",
    probability: 30,
    service: "Security audits for websites and apps",
    reasoning: "A high‑profile fashion mall with a large online presence likely needs …",
    issues: "FB-only store — perfect for AI Chatbot + Auto-Order System",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "Medium (50%)",
    status: LeadStatus.PROPOSAL_SENT,
    tags: ["fashion"],
    pitch: "সালামু আলাইকুম, Royal Malabar - Fashion Mall! আপনি FB-এ বিক্রি করছেন …",
    whatsapp_link: "https://wa.me/8801311183899",
    notes: [],
  },
  {
    advertiser: "Nogor Boyes",
    facebook_link: "https://www.facebook.com/nogorboys/",
    website_link: "FB Only",
    contact: "",
    library_id: "1032341065684116",
    probability: 68,
    service: "E-commerce website development and maintenance",
    reasoning: "A locally based, active men's clothing shop with a modest follower bas…",
    issues: "",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.LOW,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "< ৳150K",
    dm_open_rate_prediction: "Medium (50%)",
    status: LeadStatus.CLOSED_WON,
    tags: ["clothing"],
    pitch: "সালামু আলাইকুম, Nogor Boyes! আপনি FB-এ বিক্রি করছেন — কিন্তু অর্ডার ম…",
    whatsapp_link: "",
    notes: [],
  },
  {
    advertiser: "Aaron Clothing DenimX",
    facebook_link: "https://www.facebook.com/aaronclothingdenimx/",
    website_link: "FB Only",
    contact: "01708158158",
    library_id: "1415123930623234",
    probability: 70,
    service: "Securing and maintaining existing online stores",
    reasoning: "Aaron Clothing has a sizable, active Facebook presence and an existing…",
    issues: "FB-only store — perfect for AI Chatbot + Auto-Order System",
    estimated_daily_orders: "Unknown",
    ad_spend_intensity: AdSpendIntensity.MEDIUM,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "৳300K",
    dm_open_rate_prediction: "Medium (50%)",
    status: LeadStatus.CLOSED_LOST,
    tags: ["clothing"],
    pitch: "সালামু আলাইকুম, Aaron Clothing DenimX! আপনি FB-এ বিক্রি করছেন — কিন্ত…",
    whatsapp_link: "https://wa.me/8801708158158",
    notes: [],
  },
  {
    advertiser: "East-End Wear",
    facebook_link: "https://www.facebook.com/eastendwear/",
    website_link: "FB Only",
    contact: "01708158158",
    library_id: "1344481357339569",
    probability: 72,
    service: "Securing and maintaining existing online stores",
    reasoning: "East-End Wear has a professional online presence with contact info and…",
    issues: "FB-only store — perfect for AI Chatbot + Auto-Order System",
    estimated_daily_orders: "5-10",
    ad_spend_intensity: AdSpendIntensity.MEDIUM,
    cart_abandon_risk: RiskLevel.MEDIUM,
    estimated_monthly_revenue: "৳500K",
    dm_open_rate_prediction: "Medium (50%)",
    status: LeadStatus.NEW,
    tags: ["clothing"],
    pitch: "সালামু আলাইকুম, East-End Wear! আপনি FB-এ বিক্রি করছেন — কিন্তু অর্ডার…",
    whatsapp_link: "https://wa.me/8801708158158",
    notes: [],
  },
  {
    advertiser: "MAC Sourcing",
    facebook_link: "https://www.facebook.com/macsourcingbd/",
    website_link: "https://macsourcing.com/",
    contact: "01711-050587",
    library_id: "24770873882613241",
    probability: 85,
    service: "E-commerce website development and maintenance",
    reasoning: "MAC Sourcing has an established website and strong social presence…",
    issues: "",
    estimated_daily_orders: "10-20",
    ad_spend_intensity: AdSpendIntensity.HIGH,
    cart_abandon_risk: RiskLevel.LOW,
    estimated_monthly_revenue: "৳1M",
    dm_open_rate_prediction: "High (70%+)",
    status: LeadStatus.CONTACTED,
    tags: ["sourcing"],
    pitch: "সালামু আলাইকুম, MAC Sourcing! আপনার দোকানে ~৫–১৫ অর্ডার/দিন (১–৩ লাখ…",
    whatsapp_link: "https://wa.me/8801711050587",
    notes: [],
  },
  {
    advertiser: "LTM Fashion",
    facebook_link: "https://www.facebook.com/ltmfashion/",
    website_link: "https://ltmlifestyle.com/winter-wear?product_id=1160",
    contact: "",
    library_id: "1848473159374193",
    probability: 45,
    service: "Website performance optimization",
    reasoning: "LTM Fashion has an existing website that could benefit from optimization…",
    issues: "Slow loading times, poor mobile experience",
    estimated_daily_orders: "3-8",
    ad_spend_intensity: AdSpendIntensity.MEDIUM,
    cart_abandon_risk: RiskLevel.HIGH,
    estimated_monthly_revenue: "৳250K",
    dm_open_rate_prediction: "Low (<30%)",
    status: LeadStatus.QUALIFIED,
    tags: ["fashion"],
    pitch: "সালামু আলাইকুম, LTM Fashion! আপনার দোকানে ~৫–১৫ অর্ডার/দিন (১–৩ লাখ/…",
    whatsapp_link: "",
    notes: [],
  },
];

// Function to seed the database
export async function seedDatabase() {
  try {
    const response = await fetch('/api/leads/seed', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ leads: sampleLeads }),
    });

    if (!response.ok) {
      throw new Error('Failed to seed database');
    }

    const result = await response.json();
    return result;
  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  }
}